import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ReactQueryProvider } from "@/context/ReactQueryClientProvider";
import "swiper/css";
import "swiper/css/bundle";

export const metadata: Metadata = {
  title: "Kawasan Wisata Ngarai Sianok",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={` font-nunito   antialiased`}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
